### ISSUE TITLE
can't connect with curl

### ISSUE THREAD

**Issue by farvardin** [nazar-pc/solax-local-api-docs#2]
hello,

I have a X1-Hybrid-G4 with a pocket lan dongle (no wifi).

I can't curl with the local IP to the system:

> curl -d "optType=ReadRealTimeData&pwd=xxxxxx" -X POST http://192.168.1.45

> curl: (7) Failed to connect to 192.168.1.45 port 80 after 4 ms: Connexion refusée

the IP is correct (I can ping it, and it disappears if I remove the dongle), the pwd should be correct as well, I can use it to query the system in the "cloud", with : 

> https://www.solaxcloud.com/proxyApp/proxy/api/getRealtimeInfo.do?tokenId=xxxx&sn=xxx

and a get a json file with "Query success!" in it.

I want to access this inverter in local, not to be dependant on the solax website...

Do you have any idea why it isn't working? Maybe the wifi version needs to be connected to, so there isn't anything which prevents it from being accessed from the  port 80?

**Comment by nazar-pc** [comment]
I think the reason is that Pocket LAN is not identical to Pocket WiFi and may not even expose any data at all since you're not connecting to it with an app, it is just there to send data to Solax's servers.

If you figure out how to access it and send a PR with documentation updates, I'll be happy to accept it, otherwise there isn't anything I can do here.
